### ISSUE TITLE
Proxy issue with content-length?

### ISSUE THREAD

**Issue by lfvdaniel** [camel-tooling/camel-lsp-client-vscode#1922]
# Issue information

I'm using this extension in a environment that is behind a corporate proxy and I "always" get the error attached in the screenshot. Also check the error log below from output.

Am i missing some config or do anyone know why this is happening?

## Environment

- Language Support for Apache Camel version: **v1.4.0**
- Linux ubuntu 22.04
- vscode 1.93
- java17

## Description of wrong behavior

The language support and auto completion doesn't work.

```BASH
[Error - 10:48:18 AM] Stopping server failed
Error: Stopping the server timed out
	at /home/u30485/.vscode/extensions/redhat.vscode-apache-camel-1.4.0/node_modules/vscode-languageclient/lib/common/client.js:983:23
[Error - 10:48:18 AM] Stopping server failed
Error: Stopping the server timed out
	at /home/u30485/.vscode/extensions/redhat.vscode-apache-camel-1.4.0/node_modules/vscode-languageclient/lib/common/client.js:983:23
[Error - 10:48:20 AM] Server process exited with signal SIGKILL.
```

## Exact steps to reproduce issue

1. Open a camel project and wait a ~1 minute then the error appears.

### Expected behaviour

Language Support for Apache Camel to work behind a proxy.

### Screenshot

![Screenshot from 2024-09-10 10-48-35](https://github.com/user-attachments/assets/4376acbc-3244-4d86-a964-e4dd3d418d9e)

BR
/Daniel

**Comment by apupier** [comment]
Do you have more information how the proxy is configured on the machine?

Can you have a look to the /tmp/log-camel-lsp.log and check if there is a stacktrace with more specific details?

Maybe need to configure Java with the proxy globally set the environment variable JAVA_TOOLS_OPTIONS https://docs.oracle.com/javase/8/docs/platform/jvmti/jvmti.html#tooloptions with the proxy configuration https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html
